### ISSUE TITLE
File.Find does not fail if access is denied to fileshare

### ISSUE THREAD

**Issue by juralaakkonen** [FrendsPlatform/Frends.File#1]
Trying to find files from a fileshare, where FRENDS Agent user does not have rights to, does not throw an exception. It ends successfully.

**Comment by nickeeex** [comment]
Fixed task here. Will appear on frends myget feed at a later time

[Frends.File.0.7.28.nupkg.zip](https://github.com/FrendsPlatform/Frends.File/files/1094029/Frends.File.0.7.28.nupkg.zip)
