### ISSUE TITLE
Rename task deletes file if nothing to rename

### ISSUE THREAD

**Issue by pekkatki** [FrendsPlatform/Frends.File#13]
Frends.File.Rename (1.0.33)

If user defines the "New file name" e.g. #var.filename.Replace("Ã¤", "ä").Replace("Õ¤", "Ö") and #var.filename does not contain characters that are to be replaced, the file in question is deleted.

What should happen is that if there is nothing to rename, the filename stays as it is and the file is not deleted.

**Comment by ttossavainen** [comment]
This bug occurs when FileExistsAction.Overwrite and target file exists.

Changes in review: 
- An exception is thrown if input.NewFileName is empty or/and input.Path doesn't exists. 
- If target file already exists,
- - FileExistsAction.Overwrite will overwrite the target file and delete the original file if both the original and new files match in size. Throwing an exception if size doesn't match.
- - FileExistsAction.Rename will now append number to name given in Input.NewFileName.
