### ISSUE TITLE
[Obsolete, moved to another repo] Frends.File.LocalBackup

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/Frends.File#16]
- Cobalt as example (https://github.com/FrendsPlatform/Frends.Cobalt/tree/master#source)
    - There is a local backup in Cobalt processing steps, which we essentially need to do here
- Needs input (files to be backed up)
    - Dir and file mask
- Needs backup settings
    - Backup dir
    - Switch for cleanup
    - Cleanup setting (visible only when cleanup needed)

NB! SUPPORT BOTH .NET 6 and .NET STANDARD 2.0

**Comment by ttossavainen** [comment]
This will be handled in https://github.com/FrendsPlatform/Frends.Files/issues/1
