### ISSUE TITLE
Copy task requires write permissions to source file

### ISSUE THREAD

**Issue by KRuusuv** [FrendsPlatform/Frends.File#17]
The copy task opens a filestream with read/write access using System.IO.File.Open(sourceFilePath, FileMode.Open). However, read permissions should be enough for copying, so System.IO.File.Open(sourceFilePath, FileMode.Open, FileAccess.Read) would be a more intuitive choice.

**Comment by jannek-aalto** [comment]
Over a year later, this ridiculously simple but production show-stopper issue is still here.

**Comment by RikuVirtanen** [comment]
This was fixed in PR #20
