### ISSUE TITLE
Memory leak in ExecuteWriteBytes method

### ISSUE THREAD

**Issue by helvertti** [FrendsPlatform/Frends.File#19]
using (var fileStream = new FileStream(input.Path, fileMode, FileAccess.Write, FileShare.Write, 4096, useAsync: true))
{
var memoryStream = new MemoryStream(bytes);
await memoryStream.CopyToAsync(fileStream).ConfigureAwait(false);
}

var memorystream kohdasta puuttuu using.

**Comment by RikuVirtanen** [comment]
This has been fixed in the new official .NET6 Tasks https://github.com/FrendsPlatform/Frends.Files/issues/46
