### ISSUE TITLE
File.Copy and File.Move - Impersonation only works on .net461 because of #if preprocessor

### ISSUE THREAD

**Issue by RikuVirtanen** [FrendsPlatform/Frends.File#25]
Noticed that the Task doesn't work on Frends when using impersonation a.k.a Use given user credentials for remote connections setting even if the process is targeting framework 4.7.1. This is because the  #if preprocessor is too strict: https://github.com/FrendsPlatform/Frends.File/blob/e3ff453ec9da1cc5367fcb92a6f2bc4613f006e9/Frends.File/File.cs#L141-L148

The impersonation worked in version 1.1.36 because the project target was then net461, but after the last change the target was changed what caused the impersonation to not work on newer targets.

**Comment by jsalmela** [comment]
We have the same issue and can't use the new crossplatform  version Frends.Files.Move  yet, so is it possible to fix this?

**Comment by ltuuri** [comment]
Yes, we se this too. Please fix current Frends.File version to work on FrameWork 4.7.1 based environments too!

**Comment by RikuVirtanen** [comment]
This has now been fixed in the newest release.
#26
