### ISSUE TITLE
It is not checked if Directory is valid path or not.	

### ISSUE THREAD

**Issue by OssiGalkin** [FrendsPlatform/Frends.File#3]
At the moment, Directory property in input parameters in Move and Find tasks (and maybe in other tasks as well), can contain any string. If the string is not valid path error is not raised. This is annoying when one does insert Directory as environment variable and forgets to change parameter type from Text to Expression. In that case task tries to find path starting #env.something.... 

If it is not possible to check if Directory parameter is valid in general, it should be checked if it starts with character '#' and then raise error if it does, because Windows paths are something like C:\blah and unix paths are like /user/blah

**Comment by jvuoti** [comment]
This seems to have been fixed with issue #1: If you are trying to copy of find files from a directory that does not exist, an error will be thrown instead of just returning nothing. So closing down as a duplicate.
